pipeline {
    agent any
    tools {
        maven "maven-3.9"
    } 
    stages {
        stage("buildApp") {
            steps {
                script {
                    echo "building the application..."
                    sh "mvn package"
                }
            }
        }

        stage("deploy") {
           steps {
            script {
                 echo "building docker image of the appliction..."
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "docker build -t amosa77/demo-app:jma-2.4 ."
                    sh "echo $PASSWORD | docker login -u $USERNAME --password-stdin"
                    sh "docker push amosa77/demo-app:jma-2.4"
                }
            }
           }
        }

        stage("deployApp") {
            steps {
                script {
                    echo "deploying the application..."
                }
            }
        }

    }

}
